---
apiVersion: v1
kind: Service
metadata:
  name: opencds
spec:
  type: ClusterIP
  selector:
    app: opencds-rckms
  ports:
  - port: 8080
    name: opencds-rckms-port
    targetPort: tomcat-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opencds-rckms
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opencds-rckms
    spec:
      tolerations:
      - key: preemptible
        operator: Equal
        value: "1"
        effect: NoSchedule
      containers:
      - name: opencds-rckms
        image: opencds-rckms
        imagePullPolicy: Never
        ports:
        - name: tomcat-web
          containerPort: 8080
